### ISSUE TITLE
window.Immutable

### ISSUE THREAD

**Issue by dantman** [HubSpot/general-store#34]
GeneralStore uses `window.Immutable` in the code.
```js
var compare = window.Immutable && typeof window.Immutable.is === 'function' ? window.Immutable.is : function (a, b) {
  return a === b;
};
```

This use of `window` means that `general-store` cannot be required at all on the server because a ReferenceError is thrown when `window` is accessed.

Also, when Immutable is loaded as a module it does not define Immutable on `window`. This means that if `general-store` and `immutable` are required by browserified code GeneralStore will not use `Immutable.is`.

**Comment by colbyr** [comment]
should be resolved as of #36
