### ISSUE TITLE
handle focus when `BaseComponent` is an object

### ISSUE THREAD

**Issue by akutch** [HubSpot/general-store#66]
In cases where we use`forwardRef`, `forwardRef` returns an object rather than a react class/function. This means that  `BaseComponent.prototype` is `undefined` and causes the following error:

![Screen Shot 2019-04-18 at 10 37 16 AM](https://user-images.githubusercontent.com/6456722/56368704-fba72e80-61c5-11e9-9615-c11cf6b9a9ec.png)

**Comment by FranDias** [comment]
<img width="398" alt="Screenshot 2019-04-18 10 56 38" src="https://user-images.githubusercontent.com/557952/56370105-a7ea1480-61c8-11e9-8ea0-f7985e4ca34c.png">
😮

**Comment by Friss** [comment]
I just ran into this in a side project and while adding a check for `BaseComponent.prototype` would work the other problem is that we still always set a `ref`. 

We could make that conditional as well in the case of an arrow function component. I tried briefly looking into using `React.forwardRef` but I think that opens a big can of worms.

**Comment by aem** [comment]
fixed in #83
